name: PrettierExplosions
description: Stunning realistic tnt & explosion visuals. Respects fps, protection, and claiming plugins.
author: kixmc
version: 1.0.1
main: com.kixmc.PE.core.PrettierExplosions
api-version: 1.21
commands:
  prettierexplosions:
    aliases: [pe]